### ISSUE TITLE
add mntray.desktop to autostart

### ISSUE THREAD

**Issue by schinfo** [moson-mo/mntray#1]
Can you include an autostart for mntray, please.

You have to copy the file `mntray.desktop` to the path `~/.config/autostart` (~ it's the home-dirctory of the user)
I cann't do that in PKGBUILD, because there's no right to write into the home-directory of the user.
It's only possible in your source-code.

**mntray.desktop** includes

`[Desktop Entry]`
`Name=mntray`
`Type=Application`
`Exec=/usr/bin/mntray`
`X-GNOME-Autostart-enabled=true`
`NoDisplay=false`
`Hidden=true`
`X-GNOME-Autostart-Delay=0`

**Comment by moson-mo** [comment]
Hi. Thanks.
Hidden=true prevents it from starting. I assume that should be "true" instead?

**Comment by schinfo** [comment]
Hidden=true should be right - mntray.desktop was created by the system

**Comment by moson-mo** [comment]
With true it does not start on xfce, gnome and kde. It has to be false for autostart

**Comment by schinfo** [comment]
https://arcolinux.com/how-to-autostart-any-application-on-any-linux-desktop/

**Comment by moson-mo** [comment]
Added .desktop file
