### ISSUE TITLE
[Update] Add support for the new categories

### ISSUE THREAD

**Issue by FrogMcRibbit** [moson-mo/mntray#2]
Manjaro forum now has 2 new categories inside announcements: News and Releases. Is mntray already compatible with those new categories or it needs some adjustments to support those?

**Comment by moson-mo** [comment]
Thanks for the info.
See forum post for more info. I will add those new categories later.

https://forum.manjaro.org/t/mntray-manjaro-announcements-tray-app/107094/113?u=moson

**Comment by moson-mo** [comment]
New version 1.0.3 has been published...
