### ISSUE TITLE
Please add a binary for windows on the releases page

### ISSUE THREAD

**Issue by nazibalalam** [moson-mo/mntray#5]
Hey, this app was amazing. I love it. But I'm very that there are no binaries available for windows :( Of course, building it myself would be very easy as the app is written in go. But that's also a strong reason why you should include a binary for windows. I hope you do that :)

**Comment by moson-mo** [comment]
Sorry, I have no interest in providing Windows binaries.
As you say, you can build it yourself also.

I'm not sure if it'll work properly ootb though. Some code changes might be required. 🤷‍♂️
